include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_this: true
    prefer_final_fields: true
    use_key_in_widget_constructors: true
    always_declare_return_types: true
    file_names: true
    camel_case_types: true
